- name: ansible-sdkman
  src: https://github.com/Comcast/ansible-sdkman.git
  version: master
  scm: git
- name: ansible-spotify
  src: https://github.com/KernelPanicAUS/ansible-spotify.git
  version: master
  scm: git
- name: ansible-vscode
  src: https://github.com/ngetchell/vscode.git
  version: master
  scm: git
- name: ansible-nvm
  src: https://github.com/stephdewit/ansible-nvm.git
  version: master
  scm: git
- name: ansible-pyenv
  src: https://github.com/dylanninin/ansible-pyenv.git
  version: master
  scm: git
- name: jetbrains-toolbox
  src: https://github.com/jaredhocutt/ansible-jetbrains-toolbox.git
  version: master
  scm: git
- name: ansible-tfenv
  src: https://github.com/giner/ansible-role-tfenv.git
  version: main
  scm: git
