---
- name: Add ykman repository from PPA and install its signing key on Ubuntu target
  ansible.builtin.apt_repository:
    repo: ppa:yubico/stable

- name: Add gcloud signing key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: Add gcloud repository
  apt_repository: repo='deb https://packages.cloud.google.com/apt cloud-sdk main'

- name: .rpm upgrade server
  yum: >
    update_cache=yes
    name=*
    state=latest
    update_cache=yes
  when: >
    ansible_distribution == 'CentOS'
    or
    ansible_distribution == 'RedHat'

- name: .deb do dist-upgrade
  apt: >
    update_cache=yes
    cache_valid_time=1200
    upgrade=dist
  when: >
    ansible_distribution == 'Debian'
    or
    ansible_distribution == 'Ubuntu'
    or
    ansible_distribution == 'Pop!_OS'

- name: Install Packages
  apt:
    pkg:
     - "{{item}}"
    state: latest
    update_cache: true
  with_items:
      - tmux
      - build-essential
      - git
      - vim
      - neovim
      - python3-jmespath
      - python3-pip
      - pcscd
      - yubikey-manager
      - scdaemon
      - gnupg
      - pinentry-qt
      - cargo
      - alacritty
      - apt-transport-https
      - ca-certificates
      - google-cloud-sdk

- name: Check that rancher-desktop is installed
  stat:
    path: /usr/bin/rancher-desktop
  register: rancher_desktop_result

- name: Download rancher-desktop
  get_url: > 
    url="https://github.com/rancher-sandbox/rancher-desktop/releases/download/v0.6.0/rancher-desktop_0.6.0_amd64.deb"
    dest="/home/{{ ansible_env.USER }}/Downloads/rancher-desktop_0.6.0_amd64.deb"
  when: not rancher_desktop_result.stat.exists

- name: Install rancher-desktop
  apt:
    deb: "/home/{{ ansible_env.USER }}/Downloads/rancher-desktop_0.6.0_amd64.deb"
  when: not rancher_desktop_result.stat.exists

- name: Check that 1pasword is installed
  stat:
    path: /usr/bin/1password
  register: one_password_result

- name: install 1Password
  apt:
    deb: "https://downloads.1password.com/linux/debian/amd64/stable/1password-latest.deb"
  when: not one_password_result.stat.exists

